In [2]:
def divisores(n):
    lista=[]
    for i in range (1,n+1):
        if n%i==0:
            lista.append(i)
    return lista

if __name__=='__main__':
    n=int(input("Introduzca un número positivo: "))
    listaDivisores = divisores(n)
    print(listaDivisores)


Introduzca un número positivo:  78


[1, 2, 3, 6, 13, 26, 39, 78]


In [2]:
import numpy as np

def rellenarVector(n):
    lista=[]
    for i in range(n):
        dato = int(input(f"V[{i}]: "))
        lista.append(dato)
    return lista

if __name__=='__main__':
    n=int(input("Introduzca el número de componentes del primer vector: "))
    s=int(input("Introduzca el número de componentes del segundo vector: "))
    vector1=rellenarVector(n)
    vector2=rellenarVector(s)
    prodEsc=np.dot(vector1,vector2)
    print(prodEsc)

Introduzca el número de componentes del primer vector:  3
Introduzca el número de componentes del segundo vector:  3
V[0]:  2
V[1]:  3
V[2]:  425
V[0]:  25
V[1]:  2
V[2]:  42


17906


In [15]:
import random

def generarAleatorios(n,a,b):
    lista=[]
    for i in range (n):
        valor=random.randint(a,b)
        lista.append(valor)
    return lista

def invertirLista(lista):
    listaNew = lista[::-1]
    return listaNew
    
if __name__=='__main__':
    n=int(input("Números aleatorios: "))
    a=int(input("Número menor del intervalor: ")) 
    b=int(input("Número mayor del intervalor: ")) 
    lista = generarAleatorios(n,a,b)
    invertida = invertirLista(lista)
    print(invertida)

Números aleatorios:  9
Número menor del intervalor:  1
Número mayor del intervalor:  9


[7, 9, 2, 9, 6, 4, 1, 9, 2]


In [15]:
import numpy as np
import math

def rellenarVector(n):
    lista=[]
    for i in range(n):
        dato=int(input(f"V[{i}]: "))
        lista.append(dato)
    return lista

def calcularMedia(lista):
    media = np.mean(lista)
    return media

def calcularVarianza(lista):
    suma=0
    for i in range(len(lista)):
        suma+=pow(lista[i]-media, 2)
    return suma/len(lista)

def masAlto(lista):
    a = max(lista)
    indexAlto = lista.index(a)       
    return a, indexAlto

def masBajo(lista):
    b = min(lista)
    indexBajo=lista.index(b)
    return b, indexBajo

if __name__=='__main__':
    n=int(input("Número de alumnos: "))
    if n<=30:
        lista=rellenarVector(n)
        media=calcularMedia(lista)
        varianza=calcularVarianza(lista)
        alto=masAlto(lista)
        bajo=masBajo(lista)
        print("La media es", media, "y la varianza", varianza)
        print("El más alto y su posición respectivamente es", alto)
        print("El más bajo y su posición respectivamente es", bajo)
    else:
        print("El número de alumnos debe de ser menos de 30")

Número de alumnos:  7
V[0]:  1
V[1]:  5
V[2]:  7
V[3]:  4
V[4]:  2
V[5]:  7
V[6]:  5


La media es 4.428571428571429 y la varianza 4.53061224489796
El más alto y su posición respectivamente es (7, 2)
El más bajo y su posición respectivamente es (1, 0)


In [45]:
import random
import numpy as np

def rellenarManual(M):
    for i in range(M.shape[0]):
        for j in range(M.shape[1]):
            M[i, j] = int(input(f"M[{i}, {j}: ]"))
            
def rellenarAuto(M,a,b):
    for i in range(M.shape[0]):
        for j in range(M.shape[1]):
            M[i,j]=random.randint(a,b)

if __name__=='__main__':
    M=np.zeros((3,3))
    rellenarManual(M)
    print(M)
    a=int(input("Primer valor de intervalo: "))
    b=int(input("Segundo valor de intervalo: "))
    if b<a:
        a,b=b,a
    rellenarAuto(M,a,b)
    print(M)
    

M[0, 0: ] 1
M[0, 1: ] 5
M[0, 2: ] 3
M[1, 0: ] 5
M[1, 1: ] 4
M[1, 2: ] 3
M[2, 0: ] 5
M[2, 1: ] 4
M[2, 2: ] 3


[[1. 5. 3.]
 [5. 4. 3.]
 [5. 4. 3.]]


Primer valor de intervalo:  9
Segundo valor de intervalo:  1


[[1. 3. 6.]
 [9. 5. 9.]
 [8. 5. 4.]]


In [63]:
import numpy as np

def rellenarManual(M, nombreMatriz):
    for i in range(M.shape[0]):
        for j in range(M.shape[1]):
            M[i,j]= int(input(f"{nombreMatriz}[{i},{j}]: "))
            
def rellenarAutomatico(M,a,b):
    for i in range (M.shape[0]):
        for j in range (M.shape[1]):
            M[i,j]=random.randint(a,b)

if __name__=='__main__':
    nFil1=int(input("Número de filas: "))
    nCol1=int(input("Número de columnas: "))
    nFil2=int(input("Número de filas: "))
    nCol2=int(input("Número de columnas: "))
    n=int(input("Cantidad entera a sumar: "))
    M=np.zeros((nFil1,nCol1))
    D=np.zeros((nFil2,nCol2))
    rellenarManual(M, "M")
    rellenarManual(D, "D")
    print(M,D)
    Multip=M@D  
    Suma=M+D
    Resta=M-D
    sumaEntera= M+n
    print("M*D= ",Multip, "M+D= ",Suma, "M-D= ",Resta)
    print(f"M+{n}=",sumaEntera)

Primer valor de intervalo:  3
Segundo valor de intervalo:  3
Primer valor de intervalo:  3
Segundo valor de intervalo:  3
Cantidad entera a sumar:  1
M[0,0]:  2
M[0,1]:  4
M[0,2]:  5
M[1,0]:  6
M[1,1]:  7
M[1,2]:  9
M[2,0]:  9
M[2,1]:  8
M[2,2]:  8
D[0,0]:  7
D[0,1]:  5
D[0,2]:  4
D[1,0]:  3
D[1,1]:  5
D[1,2]:  4
D[2,0]:  3
D[2,1]:  4
D[2,2]:  5


[[2. 4. 5.]
 [6. 7. 9.]
 [9. 8. 8.]] [[7. 5. 4.]
 [3. 5. 4.]
 [3. 4. 5.]]
M*D=  [[ 41.  50.  49.]
 [ 90. 101.  97.]
 [111. 117. 108.]] M+D=  [[ 9.  9.  9.]
 [ 9. 12. 13.]
 [12. 12. 13.]] M-D=  [[-5. -1.  1.]
 [ 3.  2.  5.]
 [ 6.  4.  3.]]
M+1= [[ 3.  5.  6.]
 [ 7.  8. 10.]
 [10.  9.  9.]]


In [ ]:
def rellenarManual(M, nombreMatriz):
    for i in range(M.shape[0]):
        for j in range(M.shape[1]):
            M[i,j]=int(input(f"{nombreMatriz}[{i},{j}]= "))

def rellenarAutomatico(M,a,b):
    for i in range(M.shape[0]):
        for j in range(M.shape[1]):
            M[i,j]=random.randint(a,b)

if __name__=='__main__':
    nFil1=int(input("Número de filas: "))
    nCol1=int(input("Número de columnas: "))
    nFil2=int(input("Número de filas: "))
    nCol2=int(input("Número de columnas: "))
    if nFil2!=nCol1:
        print("Se debecumplir nFil1=nCol2 y nFil2=nCol")
    else:
        M=np.zeros((nFil1,nCol1))
        N=np.zeros((nFil2,nCol2))
        rellenarManual(M,"M")
        rellenarManual(N,"N")
        multiplicacion=np.dot(M,N)
        print(multiplicacion)

In [7]:
import numpy as np
import random

def rellenarAuto(M,a,b):
    for i in range(M.shape[0]):
        for j in range(M.shape[1]):
            M[i,j]=random.randint(a,b)

def media(M):
    suma=0
    for i in range(M.shape[0]):
        for j in range(M.shape[1]):
            suma+=M[i,j]
    media=suma/(M.shape[0]*M.shape[1])
    return media

if __name__=='__main__':
    nFil=int(input("Número de filas: "))
    nCol=int(input("Número de columnas: "))
    M=np.zeros((nFil,nCol))
    a=int(input("Primer valor de intervalo: "))
    b=int(input("Segundo valor de intervalo: "))
    if b<a:
        a,b=b,a
    rellenarAuto(M,a,b)
    print(M)
    resultado=media(M)
    print("La media de los valores de la matriz es ", resultado)

Número de filas:  3
Número de columnas:  3
Primer valor de intervalo:  1
Segundo valor de intervalo:  9


[[7. 7. 1.]
 [8. 7. 9.]
 [7. 7. 7.]]
60.0 3 3
La media de los valores de la matriz es  6.666666666666667


In [12]:
import numpy as np
import random

def rellenarAuto(M,a,b):
    for i in range (M.shape[0]):
        for j in range(M.shape[1]):
            M[i,j]=random.randint(a,b)

def intercambio(M,x,y):
    for i in range (M.shape[0]):
        M[i,x],M[i,y]=M[i,y],M[i,x]

if __name__=='__main__':
    nFil=int(input("Número de filas: "))
    nCol=int(input("Número de columnas: "))
    M=np.zeros((nFil,nCol))
    a=int(input("Primer valor de intervalo: "))
    b=int(input("Segundo valor de intervalo: "))
    if b<a:
        a,b=b,a
    rellenarAuto(M,a,b)
    print(M)
    x=int(input("Columna 1: "))
    y=int(input("Columna 2: "))
    if x<=nCol and y<=nCol:
        intercambio(M,x,y)
        print(M)
    

Número de filas:  3
Número de columnas:  3
Primer valor de intervalo:  1
Segundo valor de intervalo:  11


[[ 4. 10.  9.]
 [ 5.  9.  2.]
 [10. 11.  2.]]


Columna 1:  1
Columna 2:  2


[[ 4.  9. 10.]
 [ 5.  2.  9.]
 [10.  2. 11.]]


In [22]:
import numpy as np
import random

def rellenarAuto(M,a,b):
    for i in range (M.shape[0]):
        for j in range(M.shape[1]):
            M[i,j]=random.randint(a,b)

def productoDiagonal(M):
    suma=1
    for i in range(M.shape[0]):
        for j in range(M.shape[1]):
            if i==j:
              suma*=M[i,j]
    return suma

if __name__=='__main__':
    n=int(input("Dimensión de la matriz cuadrada: "))
    M=np.zeros((n,n))
    a=int(input("Primer valor de intervalo: "))
    b=int(input("Segundo valor de intervalo: "))
    if b<a:
        a,b=b,a
    rellenarAuto(M,a,b)
    print(M)
    resultado=productoDiagonal(M)
    print(resultado)
    

Dimensión de la matriz cuadrada:  3
Primer valor de intervalo:  1
Segundo valor de intervalo:  11


[[ 3. 11. 10.]
 [10.  1.  8.]
 [ 6. 10.  8.]]
24.0


In [40]:
import numpy as np
import random

def rellenarAuto(M,a,b):
    for i in range (M.shape[0]):
        for j in range(M.shape[1]):
            M[i,j]=random.randint(a,b)

def maximosFila(M):
    lista=[]
    for i in range (M.shape[0]):
        a=max(M[i])
        lista.append(a)
    return lista
    
if __name__=='__main__':
    nFil=int(input("Número de filas: "))
    nCol=int(input("Número de columnas: "))
    M=np.zeros((nFil,nCol))
    a=int(input("Primer valor de intervalo: "))
    b=int(input("Segundo valor de intervalo: "))
    if b<a:
        a,b=b,a
    rellenarAuto(M,a,b)
    print(M)
    resultado=maximosFila(M)
    print(resultado)


Número de filas:  3
Número de columnas:  3
Primer valor de intervalo:  1
Segundo valor de intervalo:  11


[[7. 6. 1.]
 [3. 5. 9.]
 [9. 9. 1.]]
[np.float64(7.0), np.float64(9.0), np.float64(9.0)]


In [38]:
def union(lista1, lista2):
    resultado = list(lista1) 
    for elemento in lista2:
        if elemento not in resultado:
            resultado.append(elemento)
    return resultado

def interseccion(lista1, lista2):
    resultado = []
    for elemento in lista1:
        if elemento in lista2 and elemento not in resultado:
            resultado.append(elemento)
    return resultado

if __name__ == "__main__":
    l1 = [1, 2, 3, 4, 5]
    l2 = [4, 5, 6, 7, 8]
    print(f"Lista 1: {l1}")
    print(f"Lista 2: {l2}")
    print(f"Unión: {union(l1, l2)}")
    print(f"Intersección: {interseccion(l1, l2)}")

Lista 1: [1, 2, 3, 4, 5]
Lista 2: [4, 5, 6, 7, 8]
Unión: [1, 2, 3, 4, 5, 6, 7, 8]
Intersección: [4, 5]


In [37]:
def validarDNI(dni):
    letras_validas = "TRWAGMYFPDXBNJZSQVHLCKE"
    
    if len(dni) != 9:
        return False
    
    parte_num = dni[:8]
    letra_usuario = dni[8].upper()
    
    if not parte_num.isdigit() or not letra_usuario.isalpha():
        return False
        
    numero = int(parte_num)
    resto = numero % 23
    letra_correcta = letras_validas[resto]
    
    return letra_usuario == letra_correcta

if __name__ == "__main__":
    dni_input = input("Introduce un DNI (8 números y 1 letra): ")
    if validarDNI(dni_input):
        print("El DNI es VÁLIDO.")
    else:
        print("El DNI es FALSO.")

Introduce un DNI (8 números y 1 letra):  49388042G


El DNI es VÁLIDO.


In [36]:
def esLuhnValido(numero_str):
    lista = [int(d) for d in numero_str]
    
    lista.reverse()
    
    suma_total = 0
    
    for i in range(len(lista)):
        valor = lista[i]
        
        if i % 2 != 0:
            valor = valor * 2
            
        suma_digitos = (valor // 10) + (valor % 10)
        
        suma_total += suma_digitos
        
    return (suma_total % 10) == 0

if __name__ == "__main__":
    tarjeta = input("Introduce número de tarjeta o IMEI para validar: ")
    tarjeta = tarjeta.replace(" ", "")
    
    if tarjeta.isdigit():
        if esLuhnValido(tarjeta):
            print("El número es VÁLIDO (Cumple Luhn).")
        else:
            print("El número NO es válido.")
    else:
        print("Error: Introduce solo números.")

Introduce número de tarjeta o IMEI para validar:  398294093284


El número NO es válido.
